fix

diff --git a/.github/workflows/test-ios-simulator.yaml b/.github/workflows/test-ios-simulator.yaml
--- a/.github/workflows/test-ios-simulator.yaml
+++ b/.github/workflows/test-ios-simulator.yaml
@@ -58,10 +58,11 @@ jobs:
       - name: Run tests
         id: tests_step
         run: >
-          if [[ "${{ matrix.device }} == 'iPhone 14'"]]; then
+          if [ "${{ matrix.device }} == 'iPhone 14'"]; then
             exit 1;
+          else 
+            exit 0;
           fi;
-          exit 0
           
       - name: Upload test outputs to artifacts
         if: success() || failure()
@@ -91,14 +92,17 @@ jobs:
           
       - name: Set failed
         id: set_failure
-        if: steps.tests_step.conclusion == 'failure'
-        run: echo "failure_status=failure" >> "$GITHUB_OUTPUT"
+        if: always()
+        run:  >
+          if [ "${{ steps.tests_step.conclusion }} == 'failure' ]; then
+            echo "failure_status=failure" >> "$GITHUB_OUTPUT";
+          fi;
 
       - name: Set error occurred
         id: set_error
         if: always()
         run: >
-          if [[ ("${{ steps.tests_step.conclusion }} == 'skipped'") || ("${{ steps.tests_step.conclusion }} == 'cancelled'")]]; then
+          if [ ("${{ steps.tests_step.conclusion }} == 'skipped'") || ("${{ steps.tests_step.conclusion }} == 'cancelled'")]; then
             echo "error_status=error" >> "$GITHUB_OUTPUT";
           fi;
 
