Fix Slack messages from matrix (#1396)
* Handle errors and failures for matrix
* Improve slack messages

diff --git a/.github/workflows/test-ios-simulator.yaml b/.github/workflows/test-ios-simulator.yaml
--- a/.github/workflows/test-ios-simulator.yaml
+++ b/.github/workflows/test-ios-simulator.yaml
@@ -7,18 +7,21 @@ on:
 
 jobs:
   run_tests:
-    name: Flutter ${{ matrix.flutter-version }} on ${{ matrix.device }}, ${{ matrix.os }} ${{ matrix.os_version }}
+    name: Flutter ${{ matrix.flutter_version }} on ${{ matrix.os }} ${{ matrix.os_version }} simulator
     runs-on: macos-latest
     timeout-minutes: 60
     outputs:
-      SLACK_MESSAGE_TITLE: iOS simulator
+      SLACK_MESSAGE_TITLE: Flutter ${{ matrix.flutter_version }} on ${{ matrix.os }} ${{ matrix.os_version }} simulator
       TESTS_EXIT_CODE: ${{ steps.tests_step.outputs.TESTS_EXIT_CODE }}
+      FAILURE_STATUS: ${{ steps.status_step.outputs.FAILURE_STATUS }}
+      ERROR_STATUS: ${{ steps.status_step.outputs.ERROR_STATUS }}
+      EXCLUDED_TESTS: ${{ steps.set_excluded_tests.outputs.EXCLUDED_TESTS }}
 
     strategy:
       fail-fast: false
       matrix:
-        flutter-version: ['3.7.x']
-        device: [iPhone 14, iPad (9th generation)]
+        flutter_version: ['3.10.x']
+        device_model: [iPhone 14, iPad (9th generation)]
         os: [iOS]
         os_version: ['16.2']
 
@@ -33,7 +36,7 @@ jobs:
       - name: Set up Flutter
         uses: subosito/flutter-action@v2
         with:
-          flutter-version: ${{ matrix.flutter-version }}
+          flutter-version: ${{ matrix.flutter_version }}
           cache: true
 
       - name: Preload Flutter artifacts
@@ -47,7 +50,7 @@ jobs:
         id: start_simulator
         uses: futureware-tech/simulator-action@v2
         with:
-          model: ${{ matrix.device }}
+          model: ${{ matrix.device_model }}
           os: ${{ matrix.os }}
           os_version: ${{ matrix.os_version }}
           erase_before_boot: true
@@ -56,66 +59,90 @@ jobs:
       - name: Set simulator location
         run: xcrun simctl location booted set 52.17469,21.03193
 
+      - name: Set tests to exclude
+        id: set_excluded_tests
+        run: |
+          TESTS_TO_EXCLUDE="android_app_test,\
+          service_airplane_mode_test,\
+          service_bluetooth_test,\
+          service_cellular_test,\
+          service_wifi_test,\
+          swipe_test,\
+          webview_leancode_test,\
+          webview_login_test,\
+          webview_stackoverflow_test"
+
+          target_paths=""
+          for target in $(echo $TESTS_TO_EXCLUDE | tr ',' '\n'); do
+              target_paths+="integration_test/${target}.dart,"
+          done
+
+          echo "EXCLUDED_TESTS=$TESTS_TO_EXCLUDE" >> "$GITHUB_OUTPUT"
+          echo "EXCLUDED_TESTS=$target_paths" >> "$GITHUB_ENV"
+
       - name: Run tests
         id: tests_step
         run: |
-          xcrun simctl io booted recordVideo --codec=h264 "${{ matrix.device }}.mp4" &
+          xcrun simctl io booted recordVideo --codec=h264 "${{ matrix.device_model }}.mp4" &
           recordingpid="$!"
 
           xcrun simctl spawn booted log stream --type log --color none > all_simulator_logs.txt &
           logpid="$!"
 
+          sleep 10 # See https://github.com/leancodepl/patrol/issues/1282
+
           TESTS_EXIT_CODE=0
-          patrol test \
-            --exclude integration_test/android_app_test.dart \
-            --exclude integration_test/service_airplane_mode_test.dart \
-            --exclude integration_test/service_bluetooth_test.dart \
-            --exclude integration_test/service_cellular_test.dart \
-            --exclude integration_test/service_wifi_test.dart \
-            --exclude integration_test/swipe_test.dart \
-            --exclude integration_test/webview_leancode_test.dart \
-            --exclude integration_test/webview_login_test.dart \
-            --exclude integration_test/webview_stackoverflow_test.dart || TESTS_EXIT_CODE=$?
+          patrol test --exclude ${{ env.EXCLUDED_TESTS }} --verbose || TESTS_EXIT_CODE=$?
 
           kill -SIGINT $recordingpid
           kill -SIGINT $logpid
           echo "TESTS_EXIT_CODE=$TESTS_EXIT_CODE" >> "$GITHUB_OUTPUT"
           exit $TESTS_EXIT_CODE
 
+      - name: Check if something went wrong
+        id: status_step
+        if: always()
+        run: >
+          if [ -z ${{ steps.tests_step.outputs.TESTS_EXIT_CODE }} ]; then 
+            echo "ERROR_STATUS=error" >> "$GITHUB_OUTPUT";
+          elif [ ! ${{ steps.tests_step.outputs.TESTS_EXIT_CODE }} == 0 ]; then
+            echo "FAILURE_STATUS=failure" >> "$GITHUB_OUTPUT";
+          fi;
+
       - name: Find xcresult path
-        if: success() || failure()
+        if: ${{ (failure() || success()) && contains(fromJson('["success", "failure"]'), steps.tests_step.conclusion) }}
         run: echo "XCRESULT_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "*.xcresult" -type d)" >> $GITHUB_ENV
 
       - name: Publish test report to summary
-        if: success() || failure()
+        if: ${{ (failure() || success()) && contains(fromJson('["success", "failure"]'), steps.tests_step.conclusion) }}
         uses: kishikawakatsumi/xcresulttool@v1
         with:
-          title: Patrol tests on ${{ matrix.device }}
+          title: Patrol tests on ${{ matrix.device_model }}
           upload-bundles: never
           path: |
             ${{ env.XCRESULT_PATH }}
 
       - name: Upload XCRESULT test result to artifacts
-        if: success() || failure()
+        if: ${{ (failure() || success()) && contains(fromJson('["success", "failure"]'), steps.tests_step.conclusion) }}
         uses: actions/upload-artifact@v3
         with:
-          name: Test result from ${{ matrix.device }}.xcresult
+          name: Test result from ${{ matrix.device_model }}.xcresult
           path: ${{ env.XCRESULT_PATH }}
 
       - name: Upload simulator logs to artifacts
-        if: success() || failure()
+        if: ${{ (failure() || success()) && contains(fromJson('["success", "failure"]'), steps.tests_step.conclusion) }}
         uses: actions/upload-artifact@v3
         with:
-          name: Logs from ${{ matrix.device }}
+          name: Logs from ${{ matrix.device_model }}
           path: |
             ${{ github.workspace }}/packages/patrol/example/all_simulator_logs.txt
 
       - name: Upload captured video to artifacts
-        if: success() || failure()
+        if: ${{ (failure() || success()) && contains(fromJson('["success", "failure"]'), steps.tests_step.conclusion) }}
         uses: actions/upload-artifact@v3
         with:
-          name: Captured video from ${{ matrix.device }}.mp4
-          path: ${{ github.workspace }}/packages/patrol/example/${{ matrix.device }}.mp4
+          name: Captured video from ${{ matrix.device_model }}.mp4
+          path: ${{ github.workspace }}/packages/patrol/example/${{ matrix.device_model }}.mp4
 
   call_send_slack_message:
     name: Notify on Slack
@@ -124,5 +151,8 @@ jobs:
     if: always()
     with:
       TESTS_EXIT_CODE: ${{ needs.run_tests.outputs.TESTS_EXIT_CODE }}
+      FAILURE_STATUS: ${{ needs.run_tests.outputs.FAILURE_STATUS }}
+      ERROR_STATUS: ${{ needs.run_tests.outputs.ERROR_STATUS }}
       SLACK_MESSAGE_TITLE: ${{ needs.run_tests.outputs.SLACK_MESSAGE_TITLE }}
+      EXCLUDED_TESTS: ${{ needs.run_tests.outputs.EXCLUDED_TESTS }}
     secrets: inherit
