Run more tests on Firebase Test Lab (#832)
* remove example_simple_test.dart

* add more tests on Android Test Lab

diff --git a/.github/workflows/testlab-android.yaml b/.github/workflows/testlab-android.yaml
--- a/.github/workflows/testlab-android.yaml
+++ b/.github/workflows/testlab-android.yaml
@@ -9,7 +9,7 @@ jobs:
   main:
     name: "Test on Android on Firebase Test Lab"
     runs-on: ubuntu-latest
-    timeout-minutes: 60
+    timeout-minutes: 90
 
     defaults:
       run:
@@ -63,9 +63,10 @@ jobs:
         run: ./run_android_testlab integration_test/notifications_single_test.dart
         if: success() || failure()
 
-      - name: Run notifications_many_test.dart
-        run: ./run_android_testlab integration_test/notifications_many_test.dart
-        if: success() || failure()
+      # TODO: Enable again when flakiness is fixed
+      # - name: Run notifications_many_test.dart
+      #   run: ./run_android_testlab integration_test/notifications_many_test.dart
+      #   if: success() || failure()
 
       - name: Run open_app_test.dart
         run: ./run_android_testlab integration_test/open_app_test.dart
@@ -73,4 +74,38 @@ jobs:
 
       - name: Run open_quick_settings_test.dart
         run: ./run_android_testlab integration_test/open_quick_settings_test.dart
+        if: success() || failure()
+
+      - name: Run permissions_location_test.dart
+        run: ./run_android_testlab integration_test/permissions_location_test.dart
+        if: success() || failure()
+
+      - name: Run permissions_many_test.dart
+        run: ./run_android_testlab integration_test/permissions_many_test.dart
+        if: success() || failure()
+
+      # Not implemented on Android
+      # - name: Run service_airplane_mode_test.dart
+      #   run: ./run_android_testlab integration_test/service_airplane_mode_test.dart
+      #   if: success() || failure()
+
+      # Not implemented on Android
+      # - name: Run service_bluetooth_test.dart
+      #   run: ./run_android_testlab integration_test/service_bluetooth_test.dart
+      #   if: success() || failure()
+
+      - name: Run service_cellular_test.dart
+        run: ./run_android_testlab integration_test/service_cellular_test.dart
+        if: success() || failure()
+
+      - name: Run service_dark_mode_test.dart
+        run: ./run_android_testlab integration_test/service_dark_mode_test.dart
+        if: success() || failure()
+
+      - name: Run service_wifi_test.dart
+        run: ./run_android_testlab integration_test/service_wifi_test.dart
+        if: success() || failure()
+
+      - name: Run swipe_test.dart
+        run: ./run_android_testlab integration_test/swipe_test.dart
         if: success() || failure()
